#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Apr  6 13:38:36 2021

@author: wirrbel
"""

import os

#hardcode paths 
# check for yourself by running "whereis elastix" in the command line 
elastix_bin = '/usr/bin/elastix'
transformix_bin = '/usr/bin/transformix'

#walk through folder and make transform 
sample_folder = '../atlas/'

#extract parent folder
parent_folder = os.path.split(os.path.split(sample_folder)[0])[0]
        
#hardcoded atlas to transform to 
CCF3_atlas = '../atlas/Kim_dev_atlas/CCF3/CCF2_template_25.tif'


for brain in os.listdir(sample_folder):
    
    #only take tif files along 
    if ".tif" in brain:
        
        #extract name, create new folder 
        new_foldername = brain [:-4] + "_CCF3"
        
        new_folder = os.path.join(parent_folder,new_foldername)
        
        os.mkdir(new_folder)
                
        #command 1: make new tif 
        make_tif = (transformix_bin 
               + ' -in '  + os.path.join(sample_folder,brain) 
               #+ ' -tp ' + os.path.join(parent_folder,'elastix_files/Par_rotate90degaroundX_CCF3_nrrd_directions.txt') # use this for the Kim_developmental atlases
               + ' -tp ' + os.path.join(parent_folder,'elastix_files/Par_rotate90degaroundX_Clearmap1_v02.txt') #use this for CCF2 (i.e. Clearmap 1 atlas)
               + ' -out ' + new_folder )
        
        res = os.system(make_tif)
        
        #command 2: make inverse file 
        make_inverse = (elastix_bin 
               + ' -f ' + os.path.join(new_folder,'result.tif')
               + ' -m ' + CCF3_atlas 
               + ' -p ' + os.path.join(parent_folder,'elastix_files/Par0000affine.txt') 
               + ' -p ' + os.path.join(parent_folder,'elastix_files/Par0000bspline.txt') 
               + ' -out ' + new_folder)
        
        # run command 
        res = os.system(make_inverse);
        
        #debug 
        print ("successfully ran transform for ", brain)
